print("hi welcome to mad libs in python")
print("here is your mad lib")
print("Todd was going to the COMMONNOUN1 when he found a COMMONNOUN2 \nunder the NOUN1 and VERB sally, then PROPERNOUN\njoined Todd in the COMMONNOUN3 while you tasted FOODTYPE and it \ntasted ADJECTIVE then you and PROPERNOUN went home.")
commonnoun1 = input("commonnoun1: ")
commonnoun2 = input("commonnoun2: ")
noun1 = input("noun1: ")
verb = input("verb: ")
propernoun = input("propernoun: ")
commonnoun3 = input("commonnoun3: ")
food = input("foodtype: ")
adjective = input("adjective: ")
print("here is your story: ")
print("Todd was going to the %s" % commonnoun1) 
print("when he found a %s" % commonnoun2)
print("under the %s " % noun1)
print("and %s Sally" % verb)
print("then %s joined" % propernoun)
print("you in the %s" % commonnoun3)
print("while you tasted %s" % food)
print("and it tasted %s" % adjective)
print("then Todd and %s went home." % propernoun)